### ISSUE TITLE
Global style!!!!

### ISSUE THREAD

**Issue by atefeh-akheraty** [wusb/slide-ruler#54]
Please fix fucking
* {
    margin: 0;
    padding: 0;
} 

These codes effect all of the codes.😭😭😭😭
Thanks.

**Comment by wusb** [comment]
@atefeh-akheraty  fixed https://github.com/wusb/slide-ruler/commit/6f5e9a0a6a9861b284164cb7365c775c6d2e7b00 , please upgrade to slide-ruler@1.2.2
